# Documentation: https://docs.travis-ci.com/user/languages/python/

language: python

jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - name: Python 3.7.4 on macOS
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

install:
  - ./.travis/install.sh

script:
  - ./.travis/test.sh

after_success:
  - codecov
